### ISSUE TITLE
Solicitud de cambio de nombre y permisos de escritura del repositorio.

### ISSUE THREAD

**Issue by juusechec** [udistrital/cancelacion_semestre_api#1]
Se solicita cambiar el nombre a cancelacion_semestre_api que es un nombre adecuado a como se está llamando los repos actualmente, además necesito premisos de escritura para el usuario @juusechec. Gracias @miltonparra100

**Comment by miltonparra100** [comment]
Buen Día
Se cambió el nombre y se agregó a @juusechec al proyecto.
Gracias.
